codestates-seb/seb40_main_029

server/build.gradle, server/src/main/java/com/codestates/mainproject/member/controller/MemberController.java, server/src/main/java/com/codestates/mainproject/member/dto/MemberPatchDto.java, server/src/main/java/com/codestates/mainproject/member/dto/MemberPostDto.java, server/src/main/java/com/codestates/mainproject/member/dto/MemberResponseDto.java, server/src/main/java/com/codestates/mainproject/member/entity/Member.java, server/src/main/java/com/codestates/mainproject/member/mapper/MemberMapper.java, server/src/main/java/com/codestates/mainproject/member/repository/MemberRepository.java, server/src/main/java/com/codestates/mainproject/member/role/Role.java, server/src/main/java/com/codestates/mainproject/member/service/MemberService.java, server/src/main/java/com/codestates/mainproject/todo/controller/TodoController.java, server/src/main/java/com/codestates/mainproject/todo/entity/Todo.java
멤버등록,
멤버 정보 업데이트,
멤버 검색,
멤버 전체 검색,
멤버 삭제
구현 완료.
=> feat : member CRUD 구현

server/src/main/generated/com/codestates/mainproject/mail/mapper/MailMapperImpl.java, server/src/main/generated/com/codestates/mainproject/member/mapper/MemberMapperImpl.java, server/src/main/java/com/codestates/mainproject/member/controller/MemberController.java, server/src/main/java/com/codestates/mainproject/member/dto/MemberPaletteResponseDto.java, server/src/main/java/com/codestates/mainproject/member/dto/MemberResponseDto.java, server/src/main/java/com/codestates/mainproject/member/entity/Member.java, server/src/main/java/com/codestates/mainproject/member/mapper/MemberMapper.java, server/src/main/java/com/codestates/mainproject/member/service/MemberService.java, server/src/main/java/com/codestates/mainproject/palette/entity/MemberPalette.java, server/src/main/java/com/codestates/mainproject/palette/entity/MoodPalette.java, server/src/main/java/com/codestates/mainproject/palette/entity/MoodPaletteDetails.java, server/src/main/java/com/codestates/mainproject/palette/repository/MoodPaletteDetailsRepository.java, server/src/main/java/com/codestates/mainproject/palette/repository/MoodPaletteRepository.java, server/src/main/resources/data.sql
팔레트 정보 DB에 저장하였고, 회원가입시 유저 정보에 기본 팔레트 정보 리스폰 되도록 구현하였음.
유저가 가지고 있는 팔레트 목록은 현재 null값이 떠서 추 후 수정 필요함.
=> [BE] 팔레트 정보 조회 API 구현

client/.env, client/src/api/FriendDataApi.js, client/src/api/MailDataApi.js, client/src/components/atoms/Pagination.js, client/src/components/module/AddFriend.js, client/src/components/module/FriendCard.js, client/src/components/module/Header.js, client/src/components/module/Letters.js, client/src/components/module/Modal.js, client/src/components/templates/Friends.js, client/src/redux/store.js
1. 페이지네이션 적용
2. nav 외부 클릭시 꺼지도록 함
3. 친구 삭제/추가시 새로고침 없이 화면에 적용
4. 이미 추가한 친구 다시 추가시 알림
=> Feat/ux 날아간 코드 복구

client/data/data.json, client/src/api/FriendDataApi.js, client/src/api/MailDataApi.js, client/src/components/templates/Home.js
1. refactor브랜치 생성: refactor/FriendMailMock
2.json 목업 데이터: user -> members로 수정, mails 추가
3. friend, mail api url 3001으로 변경
=> Refactor/friend mail mock 목업데이터, api url 수정

client/src/App.js, client/src/api/LoginLogoutApi.js, client/src/api/PaletteShopApi.js, client/src/components/module/AddFriend.js, client/src/components/module/BookmarkCreate.js, client/src/components/module/LetterCreate.js, client/src/components/module/Nav.js, client/src/components/module/ThemeStore.js
=> toast 알림 전체 적용

client/src/components/module/AddFriend.js, client/src/components/module/Modal.js
#140 Changes 📝
사용성 개선: 추가할 수 있는 친구 리스트에서 내 닉네임, 이미 추가한 친구 닉네임 배제
친구 추가 시 선택을 하지 않아도 추가알람이 뜨는 에러 방지
<br>
=> Refactor/friend 에러 수정, 사용성 개선

client/src/components/module/Nav.js
- 헤더 로그인 적용
- 통계모달 토스트 알림 적용
<br>
=> refactor/login 및 통계모달 토스트 알림 추가

client/src/components/module/Header.js, client/src/components/module/LookBack.js, client/src/components/module/Nav.js, client/src/components/templates/Home.js
=> fix:minorfixes

client/src/components/module/MoodSelector.js
=> fix: edit contents height

client/src/components/module/MoodSelector.js
=> fix: code fix

client/src/components/module/GoogleLogin.js
=> refactor: 로그인 리다이렉트 uri 변경

client/src/components/module/GoogleLogin.js
=> refactor: 로그인 리다이렉트 uri 하드코딩

client/src/components/module/LoginCallback.js
=> bug: 로그인 관련 콘솔 추가

client/src/api/LoginLogoutApi.js, client/src/components/module/Header.js, client/src/components/module/Nav.js
=> bug: 로그아웃 및 닉네임 에러 수정

client/src/components/module/Header.js
=> bug: 닉네임 에러 수정

client/src/components/module/Letters.js, client/src/components/module/Nav.js, client/src/components/module/ThemeStore.js, client/src/components/templates/Friends.js, client/src/components/templates/Home.js, client/src/components/templates/Signup.js
bug: accessToken 및 토스트 에러 수정
<br>
=> bug: accessToken 및 토스트 에러 수정

client/src/components/templates/Home.js, client/src/components/templates/Signup.js
=> bug: 쿠키 임포트 추가

client/src/components/templates/Friends.js
=> fix: 임시로 코멘트처리 한 부분 수정

client/src/components/atoms/input/Input.tsx, client/src/components/atoms/input/InputStyle.tsx, client/src/components/module/friend/create/AddFriend.tsx, client/src/components/module/header/bookmark/create/BookmarkCreate.tsx, client/src/components/templates/pages/signup/Signup.js
input style 분리에 따른 에러 수정..
<br>
=> Hotfix/input input style 변경

client/src/components/templates/modals/yearly/YearlyLookBack.js
=> fix: 선택한 날짜의 컬러 불러오기 함수로 뺌

client/package-lock.json, client/package.json, client/src/api/GetPointApi.js, client/src/components/atoms/input/Input.tsx, client/src/components/atoms/input/InputStyle.tsx, client/src/components/module/friend/card/FriendCard.tsx, client/src/components/module/friend/create/AddFriend.tsx, client/src/components/module/header/Header.tsx, client/src/components/module/header/bookmark/create/BookmarkCreate.tsx, client/src/components/module/letter/Letters.tsx, client/src/components/module/letter/create/LetterCreate.tsx, client/src/components/module/letter/item/LetterItem.tsx, client/src/components/templates/modals/GlobalModal.tsx, client/src/components/templates/modals/friend/Friend.tsx, client/src/components/templates/modals/letter/Letter.tsx, client/src/components/templates/modals/theme/ThemeStore.js, client/src/components/templates/modals/todo/TodoList.js, client/src/components/templates/modals/yearly/YearlyLookBack.js, client/src/components/templates/pages/home/Home.js, client/src/components/templates/pages/signup/Signup.js, client/src/index.js
#182 
* refresh 번들(useEffect, useState) 삭제
* react query로 대체
=> react query 도입

client/src/components/atoms/pagination/Pagination.tsx
pagination에서 numPages 변수 부분을 수정했습니다.
<br>
```ts
//수정 전
const numPages = Math.ceil(total / limit);
//수정 후
const numPages = total > 0 && limit > 0 ? Math.ceil(total / limit) : 1;
```
=> hotfix: friend 모달 재오픈시 에러 수정

client/src/components/templates/modals/GlobalModal.tsx
numPages 변수 수정해서 에러 해결했습니다.
<br>
```ts
//수정 전
const numPages = Math.ceil(total / limit);
//수정 후
const numPages = total > 0 && limit > 0 ? Math.ceil(total / limit) : 1;
```
=> hotfix: pagination error

client/src/components/templates/pages/mobileAlert/MobileAlert.tsx
로고(SVG)를 타입스크립트에서 인식하지 못하는 듯 함.
일단 임시로 로고를 주석처리함
<br>
=> hotfix/mobile: 로고 주석(임시)

client/src/components/module/mood/SelectorCard.js, client/src/components/templates/modals/todo/TodoList.js
리액트 쿼리 도입으로 안 쓰게 된 refresher함수 주석처리
=> hotfix/mood,todo: 안쓰는 함수 주석

client/src/components/module/friend/card/FriendCard.tsx, client/src/components/module/friend/create/AddFriend.tsx, client/src/components/module/letter/Letters.tsx, client/src/components/module/letter/item/LetterItem.tsx
=> 최신 데이터 UI에 바로 적용될 수 있도록 수정, 에러 수정 몇가지

client/src/components/module/letter/create/LetterCreate.tsx, client/src/components/templates/modals/theme/ThemeStore.js, client/src/components/templates/pages/home/Home.js, client/src/utils/useUpdatePoint.ts
useQuery에서 onSuccess시 무효화 하는 함수 때문에 발생하는 무한 req 해결.
위 함수 삭제, 대신 포인트가 수정될때 무효화하는 훅을 만들었습니다.
<br>
=> hotfix: 포인트 업데이트 훅 작성 및 적용

client/src/components/module/letter/create/LetterCreate.tsx, client/src/components/templates/modals/theme/ThemeStore.js, client/src/components/templates/pages/home/Home.js, client/src/utils/useUpdatePoint.ts
=> Dev: 포인트 업데이트 훅 추가 및 에러수정

client/src/components/module/header/user/User.tsx
=> test: 포인트 주석처리(임시)

client/src/api/GetPointApi.js, client/src/api/UserInfoAPI.ts, client/src/components/module/header/user/PointDisplay.tsx, client/src/components/module/header/user/User.tsx, client/src/components/module/letter/create/LetterCreate.tsx
=> Hotfix/member req: 쿼리 계속 수정중

client/src/components/module/friend/create/AddFriend.tsx, client/src/components/module/friend/create/Style.tsx, client/src/components/templates/modals/friend/Friend.tsx
=> Hotfix/friend: 에러 수정

client/src/components/module/header/user/User.tsx
#208 #209 #213 
유저인포쿼리 완료 후에 데이무드 쿼리를 실행할 때 displayName가 필요함..
<br>
=> hotfix: 유저인포 쿼리 처리 후로 데이무드 이동

client/src/components/module/header/user/User.tsx
#214 
로그인했을때 에러가 남.
useQuery를 조건문 밖으로 이동시킴.
<br>
=> hotfix: dayMood 쿼리 조건문 밖으로 이동

client/src/components/module/header/user/User.tsx
=> Dev 유저무드 에러 해결

client/src/components/module/modal/Style.js, client/src/components/templates/modals/IsFullModal.tsx, client/src/components/templates/modals/IsFullModalStyle.ts
#208 
새로고침시 모달 너비에 100%을 준 것이 사라지는 에러 발생.
styled compoents를 사용해 모달 컨테이너 스타일링을 따로 함.
<br>
=> Dev 모달 ui 수정

client/src/components/atoms/modal/ModalStyle.ts, client/src/components/module/header/user/User.tsx, client/src/components/module/letter/create/Style.tsx
=> Dev UI 에러 수정

client/src/components/module/header/user/User.tsx
=> hotfix: 테스트 ui 삭제

client/src/components/module/header/user/User.tsx
유저인포를 받아오면서 loading이나 error상태일때 먹통이 되어버림.
사용을 제한할 게 아니라 재로그인을 유도해야 할 것..
<br>
=> hotfix: 유저이름 loading, error 삭제

client/package-lock.json, client/package.json, client/src/index.js
=> feat: 리액트 쿼리 개발자도구 추가

client/package.json
react query, react query devtool 버전이 달라서 오류가 발생하는 것 같음.
#227 
<br>
=> hotfix: 리액트쿼리, 리액트쿼리 데브툴 버전 통일
